# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build Step
          command: ./mvnw clean package
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Test Step
          command: ./mvnw test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build
      - test
